version: 2.1

orbs:
  node: circleci/node@4.1.1
  cocoapods: dantoml/cocoapods@0.0.2

commands:
  install-node:
    steps:
      - node/install:
          node-version: 12.13.0
      - run: node --version

  install-npm-packages:
    description: "Install NPM packages"
    steps:
      - node/install-packages:
          override-ci-command: npm install --force

  install-pods-dependencies:
    description: "Install CocoaPods dependencies"
    steps:
      - run: sed -i '' 's=React/Core=React-Core=g' /Users/distiller/project/node_modules/react-native-fetch-blob/react-native-fetch-blob.podspec
      - cocoapods/install:
          use-bundler: false

  install-simulator-dependencies:
    description: "Install iOS simulator dependencies"
    steps:
      - run:
          name: "Install applesimutils"
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew
            HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils
            
jobs:
  detox-test:
    macos:
      xcode: 12.4.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - install-node
      - install-npm-packages
      - install-pods-dependencies
      - install-simulator-dependencies
      
      - run:
          working_directory: .
          name: Run iOS detox build
          command: npx detox build --configuration ios.sim.debug

      - run:
          working_directory: .
          name: Run iOS detox test
          command: npx detox test --configuration ios.sim.debug
            
  ios-release-build:
    macos:
      xcode: 12.4.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - install-node
      - install-npm-packages
      - install-pods-dependencies
      
      - run:
          working_directory: .
          name: Generate Release IPA
          command: |
            xcodebuild -scheme InstagramClone -workspace ios/InstagramClone.xcworkspace/ -configuration Release clean archive -archivePath Archive.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            cd Archive.xcarchive/Products/
            mv Applications Payload
            zip -vr Payload.zip Payload/
            mv Payload.zip InstagramClone.ipa
            zip -vr InstagramCloneIPA.zip InstagramClone.ipa 
      - store_artifacts:
          path: /Users/distiller/project/Archive.xcarchive/Products/InstagramCloneIPA.zip

workflows:
  test-and-build:
    jobs:
      - detox-test
      - ios-release-build
