version: 2.1

orbs:
  node: circleci/node@4.1.1

commands:
  install-node:
    steps:
      - node/install:
          with-cache: false
          node-version: 12.13.0
      - run: node --version

  npm-dependencies:
    description: "Get JavaScript dependencies"
    steps:
      - node/install-packages

  pods-dependencies:
    description: "Get cocoapods dependencies"
    steps:
      - run:
          name: Getting cocoapods dependencies
          working_directory: ./ios
          command: |
            sed -i '' 's=React/Core=React-Core=g' /Users/distiller/project/node_modules/react-native-fetch-blob/react-native-fetch-blob.podspec
            pod install

  simulator-dependencies:
    description: "Install iOS simulator dependencies"
    steps:
      - run:
          name: "Install applesimutils"
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew
            HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils
            
jobs:
  detox-test:
    macos:
      xcode: 12.4.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - install-node
      - npm-dependencies
      - pods-dependencies
      - simulator-dependencies

      - run:
          working_directory: .
          name: Run iOS detox build
          command: npx detox build --configuration ios.sim.debug

      - run:
          working_directory: .
          name: Run iOS detox test
          command: npx detox test --configuration ios.sim.debug
            
  ios-release-build:
    macos:
      xcode: 12.4.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - install-node
      - npm-dependencies
      - pods-dependencies
      
      - run:
          working_directory: .
          name: Generate Release IPA
          command: |
            xcodebuild -scheme InstagramClone -workspace ios/InstagramClone.xcworkspace/ -configuration Release clean archive -archivePath Archive.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            cd Archive.xcarchive/Products/
            mv Applications Payload
            zip -vr Payload.zip Payload/
            mv Payload.zip InstagramClone.ipa
            zip -vr InstagramCloneIPA.zip InstagramClone.ipa 
      - store_artifacts:
          path: /Users/distiller/project/Archive.xcarchive/Products/InstagramCloneIPA.zip

workflows:
  test-and-build:
    jobs:
      - detox-test
      - ios-release-build
